### ISSUE TITLE
PV Input 1 and 2 not synchronized anymore

### ISSUE THREAD

**Issue by andiweli** [nograx/ioBroker.zendure-solarflow#27] opened 2024-03-01 08:53 UTC
**Describe the bug**  
PV Input 1 and 2 aren't shown anymore.

![Bildschirmfoto 2024-03-01 um 09 52 05](https://github.com/nograx/ioBroker.zendure-solarflow/assets/11447150/52e2d09d-8ef9-49b1-a027-0788e3308611)

Don't know if it has to do with yesterdays new Hub Firmware or yesterdays Adapter upgrade to 1.1.8.

**Comment by nograx** [comment] 2024-03-01 08:55
Seems the issue is located at the new firmware from zendure. Will investigate this weekend.

**Comment by andiweli** [comment] 2024-03-01 09:11
> Seems the issue is located at the new firmware from zendure. Will investigate this weekend.

Seems they renamed the parameters "solarPower1" and "solarPower2" now.

**Comment by nograx** [comment] 2024-03-01 11:36
I've compiled version 1.1.9 which will be available in the stable channel this night. Or maybe you can install it via the "Install from Github" option in iobroker. The change with the solarPower1 and 2 is untested from my side. Maybe you can verify the change? I'm not able to install the firmware update before sunday.

**Comment by andiweli** [comment] 2024-03-01 11:59
![Bildschirmfoto 2024-03-01 um 12 46 02](https://github.com/nograx/ioBroker.zendure-solarflow/assets/11447150/9436e548-efe0-4ef5-af42-47c35216159c)

Seems to work :) Thanks for the fast fix.

**Comment by nograx** [comment] 2024-03-01 12:28
Seems to be very dark on your location. Will close this issue - thanks for testing.

**Closed by nograx** 2024-03-01 12:28 UTC
Labels: bug

**Comment by andiweli** [comment] 2024-03-01 12:47
Raining all the day Am 01.03.2024 um 13:28 schrieb Peter ***@***.***>:﻿
Seems to be very dark on your location. Will close this issue - thanks for testing.
