### ISSUE TITLE
PV Input values reversed?

### ISSUE THREAD

**Issue by andiweli** [nograx/ioBroker.zendure-solarflow#25] opened 2024-02-17 11:42 UTC
**Describe the bug**  
The PV Input values in the adapter are reversed as it is shown in the App.

**To Reproduce**  
The shown values for Input 1 and 2 in the app are reversed in the adapter - means PV input 1 values from the app are the same as PV input 2 in the adapter - and vice versa.

![IMG_0033](https://github.com/nograx/ioBroker.zendure-solarflow/assets/11447150/6caf307d-972c-4004-84f0-b731791b96b9)
![IMG_0034](https://github.com/nograx/ioBroker.zendure-solarflow/assets/11447150/3d4ad8f1-9adb-4a1f-8ac0-c1b9e11879e3)

**Comment by nograx** [comment] 2024-02-19 08:17
I know this issue. The problem is that zendure did it wrong - in my opinion. I named the states like the mqtt value. I will think about it if I switch them. :-)

**Comment by nograx** [comment] 2024-02-28 09:29
Fixed in version 1.1.4

**Closed by nograx** 2024-02-28 09:29 UTC
